### ISSUE TITLE
category検索

### ISSUE THREAD

**Issue by takehanKosuke** [CA21engineer/Gotties-Server#12]
## 概要
文字列を受け取りマッチしたcategoryを配列で返す

## 提案内容
`/category/search?keyword=hogehoge`

**Comment by ry-itto** [comment]
横からごめん！
`articles` のAPIのパラメータを追加するとかだとどうだろうか？
普通に表示する時は空文字で投げて使う感じで

**Comment by ry-itto** [comment]
articles の API のパラメータに `keyword` を追加するイメージ

**Comment by takehanKosuke** [comment]
@ry-itto 
あ、ごめん今議事録見直してそもそもの勘違いが起こっていることがわかったので、これ一旦クローズしますw
